routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
      return redirect('/shares');
    } else {
      return redirect('/login');
    }

});

Route::get('/home', function(){
    return redirect('/shares');
});

Auth::routes();
Route::resource('shares', 'SharesController');


Route::post('/manualAuth', 'ManualLoginController@authenticate')->name('manualAuth');
Route::get('/showEmailUpdate', 'ManualLoginController@showEmailUpdate')->name('showEmailUpdate');
Route::post('/updateDefaultEmail', 'ManualLoginController@updateDefaultEmail')->name('updateDefaultEmail');

app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\User;

class Share extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'shares';

    protected $fillable = [
        'company_name',
        'share_instrument_name',
        'quantity',
        'price',
        'total_investment',
        'certificate_number',
        'transaction_date',
        'user_id'
    ];

    protected $dates = ['deleted_at'];

    public function user()
    {
        $this->belogsTo('App\User');
    }
}

app/Http/Controllers/SharesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

use App\Share;
use App\User;

class SharesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::check()) {
            $user_id = Auth::id();
            $shares = Share::where('user_id', $user_id)
                ->whereNull('deleted_at')
                ->orderBy('id', 'desc')
                ->paginate(10);

            return view('shares.index', ['shares' => $shares]);
        } else {
            return view('auth.login');
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::check()) {
            return view('shares.create');
        } else {
            return view('auth.login');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::check()){
            //Validate the data

            $request->validate([
                'company_name' => 'required|string|max:255',
                'share_instrument_name' => 'required|string|max:255',
                'quantity' => 'required|numeric|integer',
                'price' => 'required|numeric|',
                'certificate_number' => 'required|string|max:255',
            ]);

            DB::transaction(function () use (&$request) {
                $date_utc = new \DateTime(null, new \DateTimeZone("America/New_York"));

                DB::table('shares')->insert([
                    'company_name' => $request->input('company_name'),
                    'share_instrument_name' => $request->input('share_instrument_name'),
                    'quantity' => $request->input('quantity'),
                    'price' => $request->input('price'),
                    'total_investment' => $request->input('price') * $request->input('quantity'),
                    'certificate_number' => $request->input('certificate_number'),
                    'transaction_date' => $date_utc->format('Y-m-d'),
                    'created_at' => $date_utc->format('Y-m-d H:i:s'),
                    'updated_at' => $date_utc->format('Y-m-d H:i:s'),
                    'user_id' => Auth::id()
                ]);
            });

            $user_id = Auth::id();
            $shares = Share::where('user_id', $user_id)
                ->whereNull('deleted_at')
                ->orderBy('id', 'desc')
                ->paginate(10);

            return redirect()->route('shares.index', [
                'shares' => $shares,
            ])->with('success', 'Purchase Request has been received!');

        } else {
            return view('auth.login');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        if(Auth::check()){

            $share = Share::find($id);
            return view('shares.edit', ['share' => $share]);

        } else {
            return view('auth.login');
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::check()){
            $request->validate([
                'company_name' => 'required|string|max:255',
                'share_instrument_name' => 'required|string|max:255',
                'quantity' => 'required|numeric|integer',
                'price' => 'required|numeric|',
                'certificate_number' => 'required|string|max:255',
            ]);

            DB::transaction(function () use (&$request, &$id) {

                $date_utc = new \DateTime(null, new \DateTimeZone("America/New_York"));
                $share = Share::find($id);

                DB::table('shares')->where('id', '=', $id)->update([
                    'company_name' => $request->input('company_name'),
                    'share_instrument_name' => $request->input('share_instrument_name'),
                    'quantity' => $request->input('quantity'),
                    'price' => $request->input('price'),
                    'total_investment' => $request->input('price') * $request->input('quantity'),
                    'certificate_number' => $request->input('certificate_number'),
                    'updated_at' => $date_utc->format('Y-m-d H:i:s'),
                    'created_at' => $share['created_at'],
                ]);

            });

            $user_id = Auth::id();
            $shares = Share::where('user_id', $user_id)
                ->whereNull('deleted_at')
                ->orderBy('id', 'desc')
                ->paginate(10);

            return redirect()->route('shares.index', ['shares' => $shares])
                ->with('success', 'Purchase Request has been update successfully!');
        } else {
            return view('auth.login');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::check()){
            $findShare = Share::find($id);

            if ($findShare->delete()) {
                //redirect
                return redirect()->route('shares.index')
                    ->with('success', 'Purchase request deleted successfully');
            }
            return back()->withInput()->with('error', 'Purchase Request could not be deleted');

        } else {
            return view('auth.login');
        }

    }
}

resources/views/shares/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Purchase Reqset From</div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('shares.store') }}">
                            {{ csrf_field() }}
                            <!-- <input type='hidden' name="_method" value="PUT"/> -->
                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="company_name" class="col-md-4 control-label">Company Name <span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="company_name" type="text" class="form-control" name="company_name" value="{{ old('company_name') }}" required autofocus>

                                    @if ($errors->has('company_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('company_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('share_instrument_name') ? ' has-error' : '' }}">
                                <label for="share_instrument_name" class="col-md-4 control-label">Share Instrument Name<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="share_instrument_name" type="text" class="form-control" name="share_instrument_name" value="{{ old('share_instrument_name') }}" required autofocus>
                                    <select class="custom-select" id="inputGroupSelect01" onchange="selectOnChange()">
                                        <option selected>Choose...</option>
                                        <option value="A,B">A,B</option>
                                        <option value="Preferred">Preferred</option>
                                        <option value="Preferred">Preferred A,B</option>
                                    </select>
                                    @if ($errors->has('share_instrument_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('share_instrument_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('quantity') ? ' has-error' : '' }}">
                                <label for="quantity" class="col-md-4 control-label">Quantity<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="quantity" type="text" class="form-control" name="quantity" value="{{ old('quantity') }}" required autofocus>

                                    @if ($errors->has('quantity'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('quantity') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                                <label for="price" class="col-md-4 control-label">Price<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="price" type="text" class="form-control" name="price" value="{{ old('price') }}" required autofocus>

                                    @if ($errors->has('price'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            {{--<div class="form-group{{ $errors->has('total_investment') ? ' has-error' : '' }}">--}}
                                {{--<label for="total_investment" class="col-md-4 control-label">Total Investment<span style="color:red">*</span></label>--}}

                                {{--<div class="col-md-6">--}}
                                    {{--<input id="total_investment" type="text" class="form-control" name="total_investment" value="{{ old('total_investment') }}" required autofocus>--}}
                                    {{--@if ($errors->has('total_investment'))--}}
                                        {{--<span class="help-block">--}}
                                        {{--<strong>{{ $errors->first('total_investment') }}</strong>--}}
                                    {{--</span>--}}
                                    {{--@endif--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="form-group{{ $errors->has('certificate_number') ? ' has-error' : '' }}">
                                <label for="certificate_number" class="col-md-4 control-label">Certificate Number<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="certificate_number" type="text" class="form-control" name="certificate_number" value="{{ old('certificate_number') }}" required autofocus>

                                    @if ($errors->has('certificate_number'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('certificate_number') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Purchase
                                    </button>
                                </div>
                            </div>

                            <a class="btn btn-default" href="/">
                               Back
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shares/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Purchase Reqset From</div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('shares.update', [$share->id]) }}">
                        {{ csrf_field() }}
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="company_name" class="col-md-4 control-label">Company Name <span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="company_name" type="text" class="form-control" name="company_name" value="{{ $share->company_name }}" required autofocus>

                                    @if ($errors->has('company_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('company_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('share_instrument_name') ? ' has-error' : '' }}">
                                <label for="share_instrument_name" class="col-md-4 control-label">Share Instrument Name<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="share_instrument_name" type="text" class="form-control" name="share_instrument_name" value="{{ $share->share_instrument_name }}" required autofocus>
                                    <select class="custom-select" id="inputGroupSelect01" onchange="selectOnChange()">
                                        <option selected>Choose...</option>
                                        <option value="A,B">A,B</option>
                                        <option value="Preferred">Preferred</option>
                                        <option value="Preferred">Preferred A,B</option>
                                    </select>
                                    @if ($errors->has('share_instrument_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('share_instrument_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('quantity') ? ' has-error' : '' }}">
                                <label for="quantity" class="col-md-4 control-label">Quantity<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="quantity" type="text" class="form-control" name="quantity" value="{{ $share->quantity }}" required autofocus>

                                    @if ($errors->has('quantity'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('quantity') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                                <label for="price" class="col-md-4 control-label">Price<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="price" type="text" class="form-control" name="price" value="{{ $share->price }}" required autofocus>

                                    @if ($errors->has('price'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            {{--<div class="form-group{{ $errors->has('total_investment') ? ' has-error' : '' }}">--}}
                                {{--<label for="total_investment" class="col-md-4 control-label">Total Investment<span style="color:red">*</span></label>--}}

                                {{--<div class="col-md-6">--}}
                                    {{--<input id="total_investment" type="text" class="form-control" name="total_investment" value="{{ $share->total_investment }}" required autofocus>--}}

                                    {{--@if ($errors->has('total_investment'))--}}
                                        {{--<span class="help-block">--}}
                                        {{--<strong>{{ $errors->first('total_investment') }}</strong>--}}
                                    {{--</span>--}}
                                    {{--@endif--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="form-group{{ $errors->has('certificate_number') ? ' has-error' : '' }}">
                                <label for="certificate_number" class="col-md-4 control-label">Certificate Number<span style="color:red">*</span></label>

                                <div class="col-md-6">
                                    <input id="certificate_number" type="text" class="form-control" name="certificate_number" value="{{ $share->certificate_number }}" required autofocus>

                                    @if ($errors->has('certificate_number'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('certificate_number') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>

                        </form>
                        <a class="btn btn-default" href="/">
                            Back
                        </a>
                        <a href="#" onclick="deleteConfirm()" class="btn btn-danger">
                            Delete
                        </a>

                        <form id="delete-form" action="{{ route('shares.destroy',[$share->id]) }}"
                              method="POST" style="display: none;">
                            <input type="hidden" name="_method" value="delete">
                            {{ csrf_field() }}
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shares/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Company Name</th>
            <th>Share Instrument Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Investment</th>
            <th>Certificate Number</th>
            <th>Transaction Date</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($shares as $share)
            <tr>
                <td>{{$share->id}}</td>
                <td>{{$share->company_name}}</td>
                <td>{{$share->share_instrument_name}}</td>
                <td>{{$share->quantity}}</td>
                <td>${{$share->price}}</td>
                <td>${{$share->total_investment}}</td>
                <td>{{$share->certificate_number}}</td>
                <td>{{$share->transaction_date}}</td>
                <td>
                    <a style="cursor: pointer" href="/shares/{{$share->id}}/edit">
                        Edit
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <a class="btn btn-primary" style='float:right;' href="/shares/create">Create Request</a>
    {{$shares->render()}}

</div>

@endsection